#!/bin/bash
#SBATCH -A CS4380_CS5351 # account name
#SBATCH -J p1_fractal    # job name
#SBATCH -o p1_fractal.%j # name of the output and error file
#SBATCH -N 1             # total number of nodes requested
#SBATCH -n 1             # total number of tasks requested
#SBATCH -p normal        # queue name
#SBATCH -t 00:01:00      # expected maximum runtime (hh:mm:ss)

./fractal 250 30
./fractal 250 60
./fractal 500 30
./fractal 500 60

date

